### ISSUE TITLE
Unknown symbols don't throw an error

### ISSUE THREAD

**Issue by sheegl** [emacs-lsp/lsp-java#11] opened 2017-09-05 13:38 UTC
I just set up lsp-mode and lsp-java as the README.mds suggested. And this code doesn't result in errors. 

```
public class Main {
    public static void main(String[] args) {
       abc.def();
    }
}
```

Is there more to the setup of the language server than the README shows?

**Comment by seagle0128** [comment] 2017-10-23 15:15
Doesn't work for me as well. Don't know how to setup :(

Errors:
```elisp
user-error: No definitions found for: foo
Error from the Language Server: no identifier found (Unknown error)
```

**Comment by vibhavp** [comment] 2017-10-23 15:48
Can you try adding this to your .emacs and see whether that fixes it?

```lisp
(require 'flycheck)
(lsp-flycheck-add-mode 'java-mode)
(global-flycheck-mode 1)
```

**Comment by seagle0128** [comment] 2017-10-23 16:03
Nop for me. I think it's not related to flycheck settings.
Waiting for @tepf 's feedback.

**Comment by vibhavp** [comment] 2017-10-23 16:31
Do unknown symbols show errors in VSCode?

**Comment by seagle0128** [comment] 2017-10-24 03:16
no error in VSCode.

I digg out the root cause finnaly. I fount this message in `*lsp-java stderr*`.
```elisp
Error: Unable to access jarfile Found more than one java language server entry points: (/home/avamar/.emacs.d/eclipse.jdt.ls/server/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar /home/avamar/.emacs.d/eclipse.jdt.ls/server/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar.pack.gz)

Process lsp-java stderr finished
```
I deleted all `*.pack.gz* in the `plugins` folder, and restart Emacs. It works well now.

**Comment by tepf** [comment] 2017-10-26 19:46
Deleting `*pack.gz` files in the `plugins` directory me too. But now Emacs freezes when I try to tab complete. It's generally pretty slow as well.

**Comment by yyoncho** [comment] 2018-05-06 17:43
Fixed with https://github.com/emacs-lsp/lsp-java/pull/21 . The warnings/errors are not displayed when the file that is currently open does not have classpath configured. In latest lsp-java you have to configure the projects roots:
```elisp
(setq lsp-java--workspace-folders (list "/path/to/project1"
                                        "/path/to/project2"
                                        ...))
```

**Closed by yyoncho** 2018-05-06 17:43 UTC
