### ISSUE TITLE
eclipse/lsp4j throws Exception on "initialized" method

### ISSUE THREAD

**Issue by juergenhoetzel** [emacs-lsp/lsp-java#5] opened 2017-05-09 10:31 UTC
This is most likely a result of change 
https://github.com/eclipse/lsp4j/commit/aee5a6b410b8e63ce2de4f84ff1e7b7542a40907

```
WARNUNG: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "initialized"
}
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:49)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:108)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:165)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:136)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

  "jsonrpc": "2.0",
  "method": "initialized"
}
```

This is fixed by changing the *elisp* client from 

```elisp
   (lsp--send-notification (lsp--make-notification "initialized" nil))
```
to
```elisp
       (lsp--send-notification (lsp--make-notification "initialized" '(:dummy 1)))
```

According to  http://www.jsonrpc.org/specification#request_object:

* params

> A Structured value that holds the parameter values to be used during the invocation of the method. This member MAY be omitted.

So I consider this a eclipse/lsp4j  bug.

**Comment by vibhavp** [comment] 2017-05-09 11:44
According to the [spec](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#new-initialized-notification), `initialized` doesn't have any parameters to begin with. Also, this should send a `InvalidParams` error in return, instead of raising an exception. I'll see if I can push a workaround.

**Comment by alanz** [comment] 2017-05-09 11:58
It is a protocol V3.0 feature, perhaps we should check the response to the `initialize` message to see if it uses the version 2.0 or version 3.0 response, and send it or not accordingly.

**Comment by juergenhoetzel** [comment] 2017-05-09 13:01
> It is a protocol V3.0 feature, perhaps we should check the response to the initialize message to see if it uses the version 2.0 or version 3.0 response, and send it or not accordingly.

Current spec doesn't have this parameter, unmerged:

https://github.com/Microsoft/language-server-protocol/issues/222

**Comment by yyoncho** [comment] 2018-05-07 10:18
Closing since it is no longer reproducible with latest lsp-java and JDT. Please reopen if you hit the issue again.

**Closed by yyoncho** 2018-05-07 10:18 UTC
