### ISSUE TITLE
lsp-java command not working and timeout

### ISSUE THREAD

**Issue by fetatefog** [emacs-lsp/lsp-java#128] opened 2019-05-05 04:04 UTC
**Describe the bug**
I recently use lsp java and then I tried some command like *lsp-symbol-highlight*, *lsp-goto-type-definition*, *lsp-format-buffer*, *lsp-goto-implementation*, *lsp-java-organize-imports*. Some of them is not found in M-x, some doesn't work.

**To Reproduce**
1. I cannot find method lsp-symbol-highlight when i do M-x.
2. When my cursor at String keyword or variable, then i press M-x lsp-goto-type-definition and i got **lsp-request: Timeout while waiting for response. Method: textDocument/typeDefinition.**
3. Press M-x lsp-format-buffer in java file and i got **lsp-format-buffer: Capability not supported by the language server: "documentFormattingProvider"**
4. lsp-goto-implementation give **lsp-request: Timeout while waiting for response. Method: textDocument/implementation.**
5. lsp-java-organize-imports and i got **user-error: No to action**

**Comment by yyoncho** [comment] 2019-05-05 05:10
Closing the bug as unable to reproduce based on the following:

1. There is no such function 
2. Unable to reproduce make sure that you are using the latest jdtls server.
3. Unable to reproduce make sure that you are using the latest jdtls server.
4. Unable to reproduce make sure that you are using the latest jdtls server.
5. Unable to reproduce make sure that you are using the latest jdtls server.

Please before reopening that bug or openning another bug do:

1. Make sure that you are using the latest jdt ls
2. Attach sample project to reproduce the issue and describe the steps to reproduce including all the actions that you have performed
3. Attach the corresponding logs

**Closed by yyoncho** 2019-05-05 05:10 UTC
Labels: Unable to reproduce
