### ISSUE TITLE
lsp-java-conver-to-static-import breaks existing import

### ISSUE THREAD

**Issue by yauhen-l** [emacs-lsp/lsp-java#158] opened 2019-09-22 19:54 UTC
**Describe the bug**
If one class has both non-static and static usage of another class, then converting to static import will break non-static import. 

**Note**
Bug is reproducible on versions of lsp-java from melpa and melpa-stable: 20190918.1601 (melpa), 2.2 (melpa-stable).

**To Reproduce**
I created a project to reproduce issue and here is a problematic line:
https://github.com/yauhen-l/lsp-java-static-import-issue/blob/1469c1aed3cd3bcfc7199d0c9bcdaf764225d056/src/main/java/by/yauhenl/demo/meow/Meow.java#L9

Calling lsp-java-conver-to-static-import will fix import 
```
import by.yauhenl.demo.Foo;
```
to
```
import static by.yauhenl.demo.Foo.bar;
```
This breaks compilation of file because there is also a non-static usage of Foo class.

**Expected behavior**
Initial import line is preserved.

**Comment by yyoncho** [comment] 2019-09-23 05:30
The issue is in the jdt ls. @fbricon @testforstephen would you take a look?

**Comment by yyoncho** [comment] 2019-10-08 18:38
Closing in favour of https://github.com/eclipse/eclipse.jdt.ls/issues/1203

**Closed by yyoncho** 2019-10-08 18:38 UTC
Labels: upstream
