### ISSUE TITLE
Feature suggestion, fuzzy typing 

### ISSUE THREAD

**Issue by testinggithub1222** [emacs-lsp/lsp-java#106] opened 2019-02-26 07:54 UTC
I have using vsCode for awhile and i think that vsCode has a nice feature when we type. Imagine I have a class name UserAccount class so when i type usacc, vsCode still able to give me this option in its completion list. So, having this feature too in emacs would be great.

**Comment by yyoncho** [comment] 2019-02-27 07:13
This one has to be implemented in company-lsp, kind of a duplicate of https://github.com/tigersoldier/company-lsp/issues/79 . There   is https://github.com/PythonNut/company-flx but it works only with capf backends. (cc @tigersoldier)

**Comment by testinggithub1222** [comment] 2019-03-04 04:22
Hi @yyoncho,
> but it works only with capf backends

What does it mean by this? 

I am trying to make it works but it never works.. too bad. I may put company-backend in a wrong order. Please suggest ur configuration or this configuration. Thanks

**Comment by yyoncho** [comment] 2019-03-04 05:34
@testinggithub1222 sorry for being unclear - I meant that there is flx implementation but it is incompatible with what we currently have. AFAIK @tigersoldier is planning to implement flx matching in company-lsp at some point.

**Comment by testinggithub1222** [comment] 2019-03-04 07:10
wow, hopefully it will release soon!!

**Comment by testinggithub1222** [comment] 2019-03-04 07:16
http://www.mkyong.com/wp-content/uploads/2018/11/idea-show-method-signature-1.png
https://blog.jetbrains.com/idea/files/2010/12/quickfix-before.png

Please check link above. 
For the first picture, it shows variable name such as initialDelay, period...
For the second picture, it shows return type or parameter type such as String, void.

This is what i really mean.

**Comment by yyoncho** [comment] 2019-03-04 07:20
@testinggithub1222 I guess this comment is for the lsp-ui issue? At this point, lsp-mode displays the signature in the modeline. At some point, we may create a UI control which displays the signature info in ui frame.

**Comment by yyoncho** [comment] 2019-03-05 20:10
Closing in favour of https://github.com/tigersoldier/company-lsp/issues/89

**Closed by yyoncho** 2019-03-05 20:10 UTC
