### ISSUE TITLE
Error: void-variable treemacs-icon-java

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-java#81] opened 2018-12-07 06:20 UTC
GNU Emacs 26.1
macOS 10.14.1

```elisp
(use-package lsp-java
     :hook (java-mode . (lambda ()
                          (require 'lsp-java)
                          (lsp)))
     :config (with-eval-after-load 'treemacs
               (require 'lsp-java-treemacs)))
```

Error:

```elisp
Debugger entered--Lisp error: (void-variable treemacs-icon-java)
  (defvar treemacs-lsp-file-icon treemacs-icon-java)
  require(lsp-java-treemacs)
  (closure (t) nil (require 'lsp-java-treemacs))()
  eval-after-load(treemacs (closure (t) nil (require 'lsp-java-treemacs)))
  (progn (eval-after-load 'treemacs (function (lambda nil (require 'lsp-java-treemacs)))) t)
  (closure (t) nil (progn (eval-after-load 'treemacs (function (lambda nil (require 'lsp-java-treemacs)))) t))()
  eval-after-load(lsp-java (closure (t) nil (progn (eval-after-load 'treemacs (function (lambda nil (require 'lsp-java-treemacs)))) t)))
  (progn (use-package-ensure-elpa 'lsp-java '(t) 'nil) (eval-after-load 'lsp-java (function (lambda nil (progn (eval-after-load 'treemacs (function (lambda nil (require 'lsp-java-treemacs)))) t)))) (add-hook 'java-mode-hook (function (lambda nil (require 'lsp-java) (lsp)))))
```

**Comment by yyoncho** [comment] 2018-12-07 06:38
My first guess is that lsp-java-treemacs is missing (require 'treemacs-icons) I will take a look.

**Comment by seagle0128** [comment] 2018-12-08 16:19
I seems not working yet. Please see https://travis-ci.org/seagle0128/.emacs.d/jobs/465367722.

```elisp
Checking /home/travis/.emacs.d/elpa/lsp-java-20181208.626/icons...
Checking /home/travis/.emacs.d/elpa/lsp-java-20181208.626/icons/vscode...
Done (Total of 2 files compiled, 2 skipped)
Debugger entered--Lisp error: (void-variable treemacs-icon-java)
  (defvar treemacs-lsp-file-icon treemacs-icon-java)
  require(lsp-java-treemacs)
  (closure (t) nil (require 'lsp-java-treemacs))()
  eval-after-load(treemacs (closure (t) nil (require 'lsp-java-treemacs)))
```

**Comment by yyoncho** [comment] 2018-12-08 19:29
Now I got it - it is caused by the fact that treemacs-icon-java is not initialized if the GUI is not present.

**Comment by yyoncho** [comment] 2018-12-09 14:12
@Alexander-Miller how to solve this issue - treemacs-java-icon is part of the treemacs public interface but at the same time is not present when there is no GUI?

IMO the setup icon method could be changed to work like the define-widget in the standard library where you pass the the glyph and tag and it creates the proper mode image based on whether GUI is present or not, e. g: 

```
(define-widget 'tree-widget-close-icon 'tree-widget-icon
  "Icon for a collapsed tree-widget node."
  :tag        "[+]"
  :glyph-name "close"
  )
```

**Comment by Alexander-Miller** [comment] 2018-12-10 06:47
> treemacs-java-icon is part of the treemacs public interface but at the same time is not present when there is no GUI?

It's not just the lack of a GUI, `(image-type-available-p 'png)` must be nil for those variables to be undefined.

Let's just say this issue never came up before. Previously all I really did with those icons is put them into a hash table. For now I've pushed a patch that'll see all icons created under all circumstances.

**Comment by yyoncho** [comment] 2018-12-10 07:01
Thanks @Alexander-Miller ! @seagle0128 I believe that the issue will be fixed now.

**Closed by yyoncho** 2018-12-10 07:01 UTC

**Comment by Alexander-Miller** [comment] 2018-12-10 07:10
Hold on for a bit. CI is telling me that I broke something. I'll need to track that down first.

**Comment by Alexander-Miller** [comment] 2018-12-10 14:19
Ok, *now* things should be fixed.

**Comment by seagle0128** [comment] 2018-12-10 16:00
Thank you, both!
