### ISSUE TITLE
Go to declaration sometimes works, mostly not

### ISSUE THREAD

**Issue by oakad** [emacs-lsp/lsp-java#32] opened 2018-05-30 08:25 UTC
This happens both with M-. and C-u M-.

Looks to me like some sort of path handling bug on the elisp side.

The messages file shows the following diagnostic:

```
//... omitted
May 30, 2018 6:13:51 PM >> document/hover
May 30, 2018 6:13:51 PM >> document/documentSymbol
May 30, 2018 6:13:51 PM >> document/definition
insert-file-contents-literally: Read error: Is a directory, <directory source file is in>
May 30, 2018 6:13:51 PM >> document/documentHighlight
May 30, 2018 6:13:51 PM >> document/codeAction
```

**Comment by yyoncho** [comment] 2018-05-30 08:35
Can you retry with `toggle-debug-on-error` and paste the call stack? Can you also set `lsp-print-io` to `t` and paste the messages?

**Comment by yyoncho** [comment] 2018-05-30 08:43
I suspect that the issue is probably related to this line https://github.com/emacs-lsp/lsp-mode/blob/b0ea46230f168cf446b0dd3dbe1f0d08af2e6bb8/lsp-methods.el#L1463

**Comment by oakad** [comment] 2018-05-31 01:28
However, I don't see it happening with lsp-javascript. I have not tried it for too long, though.

**Comment by yyoncho** [comment] 2018-05-31 03:51
Are the java files in which the navigation doesnt work under any of lsp-java--workspace-folders? If they arent the navigation wont work because the project is not  loaded.

**Comment by oakad** [comment] 2018-05-31 06:02
More verbose messages.

Indeed, it appears that jdt.ls is to blame - it returns a null result. But then, it worked on another occasion with the very same file and in the very same edit sessions.

```
{
  "jsonrpc": "2.0",
  "method": "textDocument/definition",
  "params": {
    "textDocument": {
      "uri": "file:///<proper file url>"
    },
    "position": {
      "line": 77,
      "character": 34
    }
  },
  "id": 33
}
Output from language server: {
  "jsonrpc": "2.0",
  "method": "window/logMessage",
  "params": {
    "type": 3,
    "message": "May 31, 2018 3:46:20 PM >> document/definition"
  }
}
May 31, 2018 3:46:20 PM >> document/definition
Output from language server: {
  "jsonrpc": "2.0",
  "id": 33,
  "result": [
    {
      "range": null
    }
  ]
}
insert-file-contents-literally: Read error: Is a directory, <only directory here>
lsp--send-no-wait: Content-Length: 223^M
^M
{
  "jsonrpc": "2.0",
  "method": "textDocument/willSave",
  "params": {
    "textDocument": {
      "uri": "file:///<proper file url>"
    },
    "reason": 2
  }
}
lsp--send-no-wait: Content-Length: 292^M
```

**Comment by yyoncho** [comment] 2018-05-31 06:19
Based on my experience with jdt.ls it is able to find definitions consistently if the project is imported correctly. You may try to delete .emacs.d/workspace and reimport the project. Closing the bug since there is nothing we can do in `lsp-java`.

**Closed by yyoncho** 2018-05-31 06:19 UTC
