### ISSUE TITLE
Java module completing wrong

### ISSUE THREAD

**Issue by stardiviner** [emacs-lsp/lsp-java#67] opened 2018-10-24 06:24 UTC
You can see in the screenshot. When I select the `java.lang` candidate, it becomes `java.java.lang`.
![image](https://user-images.githubusercontent.com/378699/47410330-0d1ff880-d798-11e8-8052-cd41d8ec5c32.png)

And I tried `java.lang.Charact`.

![image](https://user-images.githubusercontent.com/378699/47410649-22495700-d799-11e8-9b9f-babb8490a518.png)

And it becomes this:

![image](https://user-images.githubusercontent.com/378699/47411034-1b6f1400-d79a-11e8-96e1-8ddf3d23d5af.png)

**Comment by yyoncho** [comment] 2018-10-24 06:38
This is an issue in `company-lsp` - it fails when the completion item contains .(cc @tigersoldier).

**Comment by tigersoldier** [comment] 2018-10-24 07:03
This is because company-mode and the Java language server don't agree on what's the prefix being completed - company-mode thinks it's `lang`, while the language server thinks it's `java.lang`. When confirming completion candidate, company-mode only replace `lang` with the candidate, which is `java.lang`, resulting `java.java.lang`.

The best solution is to ask the language server always populate `textEdit` in the completion items. It should inform the client (company-lsp) to replace `java.lang` with the candidate, not just `lang`.

A workaround on lsp-java side can be providing `:prefix-function` which returns `java.lang` as the prefix: 
https://github.com/emacs-lsp/lsp-mode/blob/5edc8a75e8bd2e2c4a005b20d9e86d9b4d36bb91/lsp-mode.el#L159-L162

Note that company-lsp doesn't use it yet, which I can work on if needed.

**Comment by tigersoldier** [comment] 2018-10-24 20:52
Good point. It's impossible for lsp-java to return the correct prefix.

Another possible workaround is that on completion company-lsp finds the real prefix with the given candidate, and generates pseudo text edit command based on that.

But still, the best fix remains in the language server.

**Comment by yyoncho** [comment] 2018-11-05 07:40
@tigersoldier I just want to mention that the problem is caused not by lsp server but by `company-lsp` <-> `company` interaction. The problem is that `company` inserts the candidate and then `company-lsp` fails to restore the original buffer content in order to apply text edits since the calculated prefix is incorrect.  I have described the problem in https://github.com/company-mode/company-mode/issues/790 with suggestion which will correct the insertion problem but will place incorrectly `company-mode` popup. I believe that the prefix should be calculated in the context of the candidate, for example:

``` java
java.util.Arr 
// in this case the canditate will be `java.util.ArrayList` and the  proper prefix 
// will be `java.util.Arr` not the currently calculated one - `Arr`.
```
I will do some additional research how VSCode handles this case.

CC @dgutov

**Comment by dgutov** [comment] 2018-11-05 23:11
@yyoncho Please go ahead.

> with suggestion which will correct the insertion problem but will place incorrectly company-mode popup

I'm always up to returning to that discussion, preferably once you have a more comprehensive proposal which doesn't introduce the problem you mentioned. It might not even turn out to be much bigger that the one you already described.

**Comment by j3kyl** [comment] 2018-12-02 20:19
That is happening here too!

**Comment by stardiviner** [comment] 2019-02-21 05:57
Is there any workaround for this problem? Huu, Like other lsp-mode completion client does not have this. I can accept use specific client for `lsp-java` temporaryly.

**Comment by yyoncho** [comment] 2019-02-21 06:02
@stardiviner just posted a PR - https://github.com/tigersoldier/company-lsp/pull/84 

It is not lsp-java - the issue is that only lsp-java has completion items which have the completion prefix in it (`.`) which messes up company-lsp. The only outstanding issue is the prefix calculation which is only visual - the popup wont be placed correctly.

**Comment by stardiviner** [comment] 2019-02-21 12:07
Even though I don't understand your PR code enoughtly, but it seems re-calculated the `prefix` by treat `(point-bol)` as correct bounding. Can I think this problem is solved by your PR?

**Comment by stardiviner** [comment] 2019-02-21 14:34
@yyoncho I checked out your branch `prefix-completion`. It works correctly. Awesome.

**Comment by yyoncho** [comment] 2019-02-21 17:18
@stardiviner that's good. I hope that @tigersoldier could merge it soon. I need it for making the Spring Boot Completion work too.

**Comment by tigersoldier** [comment] 2019-03-05 17:15
Hi please try this PR: https://github.com/tigersoldier/company-lsp/pull/88. Unfortunately the other PR was reverted.

**Comment by yyoncho** [comment] 2019-03-05 20:04
Closing thanks to @tigersoldier !

**Closed by yyoncho** 2019-03-05 20:04 UTC
