### ISSUE TITLE
Support Java 10

### ISSUE THREAD

**Issue by oakad** [emacs-lsp/lsp-java#34] opened 2018-05-31 06:54 UTC
It appears, that to work properly in Java 10 mode, jdt.ls may need more parameters passed in.

Judging from vscode exception:
```
if (requirements.java_version > 8) {
		params.push('--add-modules=ALL-SYSTEM',
					'--add-opens',
					'java.base/java.util=ALL-UNNAMED',
					'--add-opens',
					'java.base/java.lang=ALL-UNNAMED');
}
```

Also, gradle and maven support should not be blindly forced to "true". Jdt.ls is very sensitive to unusual project configurations and the only mode that really can be trusted to work is eclipse .project/.classfile (this is used by default when gradle and maven support are disabled in the config).

**Comment by yyoncho** [comment] 2018-05-31 20:18
I have added settings to enable/disable maven/gradle import. At this point there `lsp-java-vmargs` which can be used to inject additional parameters. When I have time I will check whether it is sufficient to make it work and then update the readme accordingly.

**Comment by oakad** [comment] 2018-06-01 01:50
Sounds good.

And thank you for the good work - my emacs java experience had improved rather considerably.

**Comment by yyoncho** [comment] 2018-06-01 07:47
No problem. As a side note, I am working on Emacs frontend for vscode debugger. I believe that I will able to make it usable in few weeks.

**Comment by va1erius** [comment] 2018-06-02 18:47
Are you talking about this one?
https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug

**Comment by yyoncho** [comment] 2018-06-02 19:01
Yes. It is an implementation of https://code.visualstudio.com/docs/extensionAPI/api-debugging .

**Comment by yyoncho** [comment] 2018-06-02 20:34
There are several things that have to be implemented and that are missing from LSP Java and LSP in general. The list is not prioritized:

1. Automatic project management - introducing commands like `lsp-add-folder`/`lsp-remove-folder` (must be implemented in `lsp-mode`)
2. Automatic installer of `jdt-ls`
3. Spacemacs layer for `lsp-java` - I have it implemented but there 2 pull requests that have to be pushed. 
4. Switching to `che-ls-jdt` . It provides support for browsing unit tests, exploring jar classes, effective pom, maven deps tree, etc.
5. Unit test support (will be in separate repo)
6. Integrated IDE-like debugger which will provide breakpoints, locals, thread, stackframe browsing, multiple session and so on which works out of the box and it is easy to use(in separate repo).
7. Code lenses support
8. IDE like folder browser(I am planning integration with `treemacs`). The idea is that you will be able to see the folders containing errors(similar to what Eclipse/Intelij do). 
9. Create `lsp-java-mode` to introduce default keybindings. 
10. Helm package for `lsp-java`/`lsp-mode`

Meanwhile, I am monitoring `jdt-ls` project for exposing any new feature. In fact, except for folder management and code lenses and few small unimportant bits, all of the `jdt.ls` functionality is accessible through `lsp-java`. 

Sadly, I have commit rights only in `lsp-java` but not in the other repos (`lsp-mode`, `lsp-ui`) slows down the items that require commits in these repos since the owners seems to be pretty busy lately and some of the pull request are pending for 10+ days. 

Also, I am trying to address all of the request/features (if feasible) to bring up more people and eventually contributors to the project. If you have some specific questions or feature requests feel free to file an issue.

**Comment by oakad** [comment] 2018-06-04 01:42
If we are already at this, what do you think about this thing here: https://github.com/joaotavora/eglot ? Is it really a better option now that Emacs 26 is out?

**Comment by yyoncho** [comment] 2018-06-04 05:00
I have filed an issue for any of the advantages that `eglot` has listed (except for prettier code). 

In my previous comment, I have listed all of the major user-visible improvements that I want to make. There are also few things that I am willing to fix under the hoods in `lsp-mode`. 

1. Better process managed. This does not affect a lot `lsp-java`(except for some startup issues) since `JDT Server` is stable, I havent encountered single crash for 3 months of usage.
2. Group edits when sending them to the server.
3. Expose more hooks - at this point `lsp-java` is using :before/:after advice to plug into `lsp-mode`.

**Comment by yyoncho** [comment] 2018-06-04 16:28
@oakad I did some testing with Java 10 but it seems like it was working fine even without the flags from comment. I am closing the issue, please reopen and provide steps to reproduce the issue or drop me a note to update README.md if the flags mentioned in bug description are required. 
![selection_034](https://user-images.githubusercontent.com/13259670/40929395-43a61680-682d-11e8-8fa0-7e43eba34998.png)

**Closed by yyoncho** 2018-06-04 16:28 UTC
